// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87ZuySgtOjfYnV1t-hR5CR3LmMB22fyE',
    appId: '1:41484707082:web:e9862a6f8ba9b72c0986f3',
    messagingSenderId: '41484707082',
    projectId: 'remiderapp-96277',
    authDomain: 'remiderapp-96277.firebaseapp.com',
    storageBucket: 'remiderapp-96277.appspot.com',
    measurementId: 'G-Q4E4Y3CVWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHuqhUQD4NLRdndfvBCE2YXmdAZgZX5s',
    appId: '1:41484707082:android:d5fb2cfeb77171980986f3',
    messagingSenderId: '41484707082',
    projectId: 'remiderapp-96277',
    storageBucket: 'remiderapp-96277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtVZjay6L5HvPl5B97oqXu9Ol1s4S1bI',
    appId: '1:41484707082:ios:9a2d84dc1237fd290986f3',
    messagingSenderId: '41484707082',
    projectId: 'remiderapp-96277',
    storageBucket: 'remiderapp-96277.appspot.com',
    iosClientId: '41484707082-j40lt1981b7es80dd037vpou00rm9uno.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireboiler',
  );
}
